### ISSUE TITLE
Episode 2: Setting Resource Location

### ISSUE THREAD

**Issue by shadowfixer** [sam-cogan/lambda-toys-api-infrastructure#10]
Hi @sam-cogan;
Thanks for the course - i really needed something that showed me how to set up Git/VSCode and get going with Bicep :) 

I have an issue with Episode 2 that i havent been able to resolve - im not asked for the value of the location parameter - so my code doesnt deploy into westeurope - i have an RG that was built by the az group create statement 
but when i try and deploy using the `az group deployment create -g lamda-api-dev --template-file .\Infrastructure\core.bicep` statement with the code below
![image](https://user-images.githubusercontent.com/72555382/199430778-53b322d9-3a4b-4cf8-9ca5-c81426dcc678.png)

i dont get prompted for a region so the networking resources don't deploy
any thoughts on where i am going wrong?
![image](https://user-images.githubusercontent.com/72555382/199493692-ab3b353a-fa6e-42d7-9a64-3238bea1c36e.png)

Thanks!

**Comment by sam-cogan** [comment]
That's odd that it's not asking you for the missing values. I'll have a look at replicating that this evening, but in the the mean time you can supply the paramters at the command line to get round this issue, just add this property to your AZ CLI command, changing values to what you desire:

```
--parameters location=westeurope prefix=dev

```

**Comment by sam-cogan** [comment]
I've tested this in PowerShell Core, PowerShell 5 and CMD and all of them do ask for the missing parameter for me. 
Can you confirm what version of the Azure CLI you're running? Could you also attach the full bicep file you are running, or paste the content into this issue?

**Comment by shadowfixer** [comment]
Hi Sam, 
Thanks for getting back to me / i do appreciate it :)
I am running Azure CLI V2.42.0 (I had to upgrade from the windows package manager version (2.41.0) to get to current version - but this makes no difference. 
I am also running Bicep CLI 0.11.1.770 if that makes a difference...
my 2 files (same issues) my file - core.bicep (my typing out your code) & sccore.bicep - copied from your episode 2 github code. 

i did notice that there is a dev.json in the configuration folder of Episode 2.... 🤷‍♂️.

Thanks
SF
[bicepfiles.zip](https://github.com/sam-cogan/lambda-toys-api-infrastructure/files/9924664/bicepfiles.zip)

**Comment by sam-cogan** [comment]
@shadowfixer the files in the zip look to be 0kb and have not content. Can you try uploading again?

The dev.json file is used a bit later in the video where we switch to using that for passing parameters rather than in the CLI, and we will do that for the rest of the course. So, if you want to skip the first run using the CLI and continue on with the video, using the parmater file will work.

**Comment by shadowfixer** [comment]
Hi there @sam-cogan ..

I think i found the problem, and its all user error - so thank you for your help & apologies for wasting your time #hangsheadinshame. 

I think the reason was that I didnt commit the core.bicep in vscode, so the AZ CLI couldnt read the "empty" file in the repos folder... 

I have a `Please provide string value for 'location' (? for help):` so all is good :) 

Thanks again!
