### ISSUE TITLE
Episode 1: Bicep Install

### ISSUE THREAD

**Issue by pmatthews05** [sam-cogan/lambda-toys-api-infrastructure#5]
Hi @sam-cogan,
I'm spending some of my day going through your Bicep for Real course. This is a great resource that you are giving away for free, and really appreciate it. 

I'm hoping by following it through, I'm giving it a sanity check, while learning myself. Any issues or inconsistency, I hope you don't mind me raising an issue for. Hopefully, if I can work out what's wrong, I'll will provide you with my steps of how I got round it.
 
---- 
With the episode 1, following your video of installing Bicep, I'm not getting the same outcome as you.

Running the following command installs Bicep.
```ps1
az bicep install
```
However, your next command does not work.
```ps1
bicep --version
```
I discovered that the following command did.
```ps1
az bicep version
```

It looks like you have installed a stand-alone version of Bicep on your computer too, or at least set up an environment path file that points to an install of Bicep. Following the link you put underneath the video for [Bicep Install](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/install) I discovered to solve the problem I needed to [Install Manually](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/install#install-manually) by following the Windows instructions for my laptop. [Manual with PowerShell](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/install#manual-with-powershell)

Soon as I did this I was able to call Bicep directly.
<img width="274" alt="image" src="https://user-images.githubusercontent.com/6736509/197730662-78344257-78d5-4287-9584-e614b0aa5f2c.png">

**Comment by sam-cogan** [comment]
That's odd that there is a difference between the commands based on how you install, I guess it's probably to fit inline with the way the azure CLI works. I'll add a note to the video.
