### ISSUE TITLE
Episode 5: Containers Part 2: Missing "hello-k8s-node" image

### ISSUE THREAD

**Issue by pmatthews05** [sam-cogan/lambda-toys-api-infrastructure#6]
In the video, it is stated that we are taking the container that the developers have pushed into the Azure Container Registry. However, some guidance for someone who hasn't worked with containers/not a developer on how to get the hello-k8s-node into the ACR so that they can follow along with the video would be useful.

I have been able to get the hello-k8s-node pushed into the ACR using these following steps. (I used the latest 1.9.0 as 1.6.0 didn't exist from the ghcr.io repository) If there was a better solution, could you please supply how. Can this be done without docker, do I always need to pull down to local machine before pushing up to ACR?

## Pre-Requisites
- Have docker desktop installed

```ps1
$registryContainerName="lmbddevacr"

az acr login --name $registryContainerName
docker login
docker pull ghcr.io/dapr/samples/hello-k8s-node:1.9.0
docker tag ghcr.io/dapr/samples/hello-k8s-node:1.9.0 "$($registryContainerName).azurecr.io/hello-k8s-node:1.9.0"
docker push "$($registryContainerName).azurecr.io/hello-k8s-node:1.9.0"
```
- Update the "containerVersion" to 1.9.0 in the dev-aca.json file
- Deploy aca.bicep

After doing this I was able to deploy aca.bicep file, and view the URL with the message "Cannot GET /".

**Comment by sam-cogan** [comment]
Hi Paul, what you did to push the container is correct, but your right I should show how to do that in the video. I'll look at adding that in.

**Comment by pmatthews05** [comment]
Thanks @sam-cogan. Do you want me to close this issue now, or leave it open until you have updated the video. (sorry to cause you more work).

**Comment by sam-cogan** [comment]
Leave it open, I'll use it to track the change.

**Comment by sam-cogan** [comment]
resolved in https://github.com/sam-cogan/BicepforReal/pull/3
