### ISSUE TITLE
Episode 6: daprComponents - Resource Type is not valid

### ISSUE THREAD

**Issue by pmatthews05** [sam-cogan/lambda-toys-api-infrastructure#7]
After updating my aca.bicep template to use the newer namespace from Microsoft.Web to Microsoft.App for the containers and daprComponents. When I've copied what you have put:
```bicep
resource daprStateStore 'daprComponents@2022-01-01-preview' = {
```
I get a wiggly red line, with a message stating the resource type is not valid. `Specify a valid resource type of format "<types>@apiVersion>"`

<img alt="image" src="https://user-images.githubusercontent.com/6736509/198034128-0fe43e3b-f8d2-4105-b759-e75466e986f7.png">

However, using a fully qualified name (is it a fully qualified name?)  as shown below, it's ok.
```bicep
resource daprStateStore 'Microsoft.App/managedEnvironments/daprComponents@2022-03-01' = {
```
<img alt="image" src="https://user-images.githubusercontent.com/6736509/198033647-868cfa75-3fb4-4ed8-aa13-a4f019dfeb17.png">

Maybe this is because I'm using a later version of Bicep than you were in the videos?

**Comment by sam-cogan** [comment]
So the reason it works in my example is that I am creating it as a sub-resource underneath the ```Microsoft.App/managedEnvironments``` resource. If you look at the example code [here](https://github.com/sam-cogan/lambda-toys-api-infrastructure/blob/7ca671a8d6a2533176c3de9b9fc3414872236af8/infrastructure/aca.bicep#LL44) it is nested underneath the top level resources, so it doesn't need the full resource type, and it doesn't need the ```parent``` link.

In your code you are creating it as a top level resource, and so you need the full path and to link it to the parent resource. Either method is valid and will work, so it depends how you prefer to create them.

**Comment by pmatthews05** [comment]
I didn't see that it was nested inside the resource. That make sense now. Thanks.
