### ISSUE TITLE
Episode 7: How do I set up the external Resource Group, Keyvault and certificate?

### ISSUE THREAD

**Issue by pmatthews05** [sam-cogan/lambda-toys-api-infrastructure#8]
Hi @sam-cogan,
 I've seemed to hit an issue that has prevented me from continuing. I'm also slightly confused.

I'm setting up the DNS record.

At 20:21 of the video you have stated you have a wildcard certificate setup in a separate resource group & key vault. From the parameters of the bicep file, these are:
- Resource Group
  - samcogancore
- KeyVaultName
  - deploymentkvsc01
- KeyVault Secret Name
  - lambdatoys

How do I set this up? From the skills you have imparted on me so far, I can create a resource group and Key Vault, but how do I configure the certificate?

Also, you set up the zone name as lambdatoys.com, is this a domain you own? Should I be able to replicate what you have done using lambdatoys.com? I'm just using a msdn azure account and dev tenant to walkthrough your examples.

**Comment by sam-cogan** [comment]
So this is mainly included as an example of using existing resources that are outside of your deployed resource group, so  you don't have to use it, you can just use the default name and SSL that MS give you if you prefer and skip this part. 

The certificate I am using here was generated from a third party (in this case it was DigiCert), certificates are pretty tricky to generate through Bicep (you can do it with an App Service certificate, but it is painful). You could also generate a self-signed certificate through key vault, it would give you an error when trying to use it in  your browser, but it would prove it was working.  [Here ](https://tsuyoshiushio.medium.com/generating-self-signed-certificate-with-keyvalt-and-enable-to-access-it-from-a-function-app-a121f6609b37) is a tutorial on doing that.

The DNS zone for lambdatoys.com is one I own. You could create an Azure DNS zone with the same name if you wanted to, and you can create the record in there with Bicep, but it won't actually resolve the name for you when trying to get your browser to hit the URL, as I have the authorative zone. You could also create your own DNS zone if you own any other domain name.s

**Comment by pmatthews05** [comment]
Thank you for the link on how to generate a self-signed certificate through key vault. I can see that the main purpose of the episode is to explain how to incorporate existing resources, which it does show.

From your getting started page:
`This course is designed to take you through step by step and build on the previous week’s work, so it is recommended you watch the classes in episode order. If you want to follow along and build the example infrastructure, you can complete the code for each episode, and you should have a deployable set of resources after each episode.
`

Your above statement on the getting started page, I expected that I would be able to run everything into my own environment. Up to this episode I have been able to. 

I feel that I'm just nit-picking. This course is great, and I have forgotten that it's purely a Bicep course. As you were using so many resources that I've never worked with before, I'm learning about those resources too. I find it would help me further to have a deployed, working example, that I can then take apart and understand the "magic" of how it all connects together.

If I don't complete anything of episode 7 in my environment, should I be able to continue from the code at the end of episode 6 directly into episode 8?

**Comment by sam-cogan** [comment]
Yep, that's a completely fair point and I agree, it would have been better to use an external resource that everyone could have setup the same, rather than being domain specific (and showing how to set this up).  

You can absolutely skip the steps in episode 7 and it won't impact the rest of the course. If you do want to try out referencing external resources the using the DNS zone part is a good way to try it out. You can still create a lambdatoys.com dns zone and have your bicep create the records in it, which will prove out that your bicep is working, it just won't resolve. 

Thanks for the feedback, it will help improve this course, or the next ones I do.

**Comment by sam-cogan** [comment]
Also, I would recommend doing the API creation part of episode 7 if you can, as it shows you how to import external json files using bicep and create APIs. All of that can be done without setting up the SSL/DNS part. 

If you skip it all, the rest of the course will still be fine, but I do think that's a useful part to do.

**Comment by sam-cogan** [comment]
Added a not to episode 7 detailing skipping the cert/dns part
